Created explorer section in template + footnote handling
webdesigndecal/mark2html pull request #3
Opened 2019-02-03 23:35 UTC by jessicamindel

Minimally modified processor to include footnote support using showdown-footnotes. Added .explorer CSS class to handle new show/hide explorer section, to be used for footnote content (envisioned as a way to include supplementary material for curious students who finish lab early or want to learn more on their own time).

<img width="720" alt="screen shot 2019-02-03 at 3 35 01 pm" src="https://user-images.githubusercontent.com/10468114/52184542-50dbc280-27c9-11e9-9d3c-8cec2f7d282a.png">

2019-02-03 23:44 UTC, jessicamindel commented
I can also go ahead and move the drop-down arrow to the right side, if it might match the rest of the document style better.

2019-02-04 08:29 UTC, thesephist requested changes
Left some small comments on the CSS section. Looks good otherwise. Thanks for being on top of the game 🚀

2019-02-04 08:31 UTC, jessicamindel commented on resources/assets/styles/style.css
> +    color: #46A03E
Oof, negligent on my part--yep, I'll fix that real quick, alongside the other suggested changes. Thank you!

2019-02-04 08:36 UTC, jessicamindel commented
Found an issue (credit to @thesephist) with how showdown-footnotes is handling footnotes--it seems to only convert the first inline footnote to a styled link (regardless of index). The rest are ignored, even though the footnotes to which they should be linking are being properly converted and styled.

2019-02-04 08:38 UTC, thesephist approved these changes

2019-02-04 08:41 UTC, merged

2019-02-04 08:53 UTC, thesephist commented
For record keeping: the bug we found is a bug in `showdown-footnotes`: https://github.com/Kriegslustig/showdown-footnotes/pull/3/commits/df4986767bd32b39c1c6babc5d2e85cc7d36de2d

It's a single-character change, but I don't think it's worth filling a PR to the original project since it doesn't look maintained. We could fork it and host it under the WDD org on NPM.

2019-02-04 08:57 UTC, jessicamindel commented
We could alternatively (if it doesn't break encapsulation or separation of concerns too much) just create a separate module within the project, since it seems like such a small extension. We'd have one fewer dependency.

2019-02-04 09:01 UTC, thesephist commented
@jessicamindel I think it's fine to just keep the dependency (I'm like 90% done forking and publishing it already lol). But you have a good point. I feel fishy about taking their code without implicitly giving credit thru the import though.

I'll make a separate PR for pulling a patched version of `showdown-footnotes` into this.

2019-02-04 09:04 UTC, jessicamindel commented
Gotcha. Yeah, agreed--credit is important. I did go ahead and try creating the second file, and made a few changes to enable backlinks on the footnotes in the footnotes section--let me know if you want me to send that over.